name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.1.0

    - name: Setup Docker Login
      uses: docker/login-action@v3.0.0
   # You may pin to the exact commit or the version.
      with:
        # Username used to log against the Docker registry
        username: alanvp301
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
