name: CI ECS Test

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
        - name: Get task file
          run: aws ecs describe-task-definition \
            --task-definition my-task-definition-family \
            --query taskDefinition > task-definition.json